import org.gradle.api.initialization.resolve.RepositoriesMode

pluginManagement {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven { url "https://plugins.gradle.org/m2/" }
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        def localProps = getLocalProps()

        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven { url "https://plugins.gradle.org/m2/" }
        gradlePluginPortal()
        maven {
            name = "GitHubPackages"
            url = "https://maven.pkg.github.com/ARK-Builders/arklib-android"
            credentials {
                username = "token"
                password = localProps.getProperty("gpr.token") ?: System.getenv("GITHUB_TOKEN")
            }
        }
        maven {
            name = "GitHubPackages"
            url = "https://maven.pkg.github.com/ARK-Builders/ark-android"
            credentials {
                username = "token"
                password = localProps.getProperty("gpr.token") ?: System.getenv("GITHUB_TOKEN")
            }
        }
    }
}

rootProject.name = "ARK Memo"
include ':app'

Properties getLocalProps() {
    def props = new Properties()
    def localPropsFile = new File(rootDir, "local.properties")

    if (localPropsFile.exists()) {
        localPropsFile.withInputStream() { stream ->
            props.load(stream)
        }
    }

    return props
}
